import {
  DeveloperProfileId,
  DeveloperProjectItemId,
  DeveloperRoleType,
  MergeRightsType,
  Owner,
  OwnerId,
  OwnerType,
  ProjectItemId,
  ProjectItemType,
  ProjectItemWithDetails,
  Repository,
  RepositoryId,
  UserId,
} from "@open-source-economy/api-types";

// Helper to create dates
const now = new Date();
const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000);
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
const yearAgo = daysAgo(365);

export const projectItemsDatabase: ProjectItemWithDetails[] = [
  // React
  {
    projectItem: {
      id: new ProjectItemId("react"),
      projectItemType: ProjectItemType.GITHUB_REPOSITORY,
      sourceIdentifier: "facebook/react",
      createdAt: yearAgo,
      updatedAt: hoursAgo(2),
    },
    owner: new Owner(
      new OwnerId("facebook", 69631),
      OwnerType.Organization,
      "https://github.com/facebook",
      "https://avatars.githubusercontent.com/u/69631",
      undefined,
      undefined,
      undefined,
      undefined,
      "Facebook",
      undefined,
      undefined,
      "https://reactjs.org",
      undefined,
      undefined,
    ),
    repository: new Repository(
      new RepositoryId(new OwnerId("facebook", 69631), "react", 10270250),
      "https://github.com/facebook/react",
      "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
      "https://reactjs.org",
      "JavaScript",
      45000,
      220000,
      undefined,
      "facebook/react",
      false,
      ["ui", "components", "javascript"],
      undefined,
      undefined,
      undefined,
      undefined,
    ),
    developers: [
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-react-1"),
          userId: new UserId("user-react-1"),
          contactEmail: "react-0@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(2),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-react-1"),
          developerProfileId: new DeveloperProfileId("dev-react-1"),
          projectItemId: new ProjectItemId("react"),
          roles: [DeveloperRoleType.CORE_TEAM_MEMBER, DeveloperRoleType.MAINTAINER],
          mergeRights: [MergeRightsType.FULL_COMMITTER],
          comment: "Core Maintainer",
          createdAt: yearAgo,
          updatedAt: hoursAgo(2),
        },
        developerOwner: new Owner(
          new OwnerId("react-0"),
          OwnerType.User,
          "https://github.com/react-0",
          "https://images.unsplash.com/photo-1743850765931-4a00e4809a5f?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Sarah Chen",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-react-2"),
          userId: new UserId("user-react-2"),
          contactEmail: "react-1@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(2),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-react-2"),
          developerProfileId: new DeveloperProfileId("dev-react-2"),
          projectItemId: new ProjectItemId("react"),
          roles: [DeveloperRoleType.MAINTAINER],
          mergeRights: [MergeRightsType.REVIEWER, MergeRightsType.LIMITED],
          comment: "Security Expert",
          createdAt: yearAgo,
          updatedAt: hoursAgo(2),
        },
        developerOwner: new Owner(
          new OwnerId("react-1"),
          OwnerType.User,
          "https://github.com/react-1",
          "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Marcus Rodriguez",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-react-3"),
          userId: new UserId("user-react-3"),
          contactEmail: "react-2@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(2),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-react-3"),
          developerProfileId: new DeveloperProfileId("dev-react-3"),
          projectItemId: new ProjectItemId("react"),
          roles: [DeveloperRoleType.ACTIVE_CONTRIBUTOR],
          mergeRights: [MergeRightsType.REVIEWER],
          comment: "Performance Lead",
          createdAt: yearAgo,
          updatedAt: hoursAgo(2),
        },
        developerOwner: new Owner(
          new OwnerId("react-2"),
          OwnerType.User,
          "https://github.com/react-2",
          "https://images.unsplash.com/photo-1526406915894-7bcd65f60845?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Priya Patel",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
    ],
  },

  // Vue.js
  {
    projectItem: {
      id: new ProjectItemId("vue"),
      projectItemType: ProjectItemType.GITHUB_REPOSITORY,
      sourceIdentifier: "vuejs/vue",
      createdAt: yearAgo,
      updatedAt: hoursAgo(5),
    },
    owner: new Owner(
      new OwnerId("vuejs", 6128107),
      OwnerType.Organization,
      "https://github.com/vuejs",
      "https://avatars.githubusercontent.com/u/6128107",
      undefined,
      undefined,
      undefined,
      undefined,
      "Vue.js",
      undefined,
      undefined,
      "https://vuejs.org",
      undefined,
      undefined,
    ),
    repository: new Repository(
      new RepositoryId(new OwnerId("vuejs", 6128107), "vue", 11730342),
      "https://github.com/vuejs/vue",
      "Progressive JavaScript framework for building modern web interfaces.",
      "https://vuejs.org",
      "TypeScript",
      34000,
      207000,
      undefined,
      "vuejs/vue",
      false,
      ["ui", "framework", "progressive"],
      undefined,
      undefined,
      undefined,
      undefined,
    ),
    developers: [
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-vue-1"),
          userId: new UserId("user-vue-1"),
          contactEmail: "vue-0@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(5),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-vue-1"),
          developerProfileId: new DeveloperProfileId("dev-vue-1"),
          projectItemId: new ProjectItemId("vue"),
          roles: [DeveloperRoleType.FOUNDER, DeveloperRoleType.CORE_TEAM_MEMBER],
          mergeRights: [MergeRightsType.FULL_COMMITTER],
          comment: "Core Maintainer",
          createdAt: yearAgo,
          updatedAt: hoursAgo(5),
        },
        developerOwner: new Owner(
          new OwnerId("vue-0"),
          OwnerType.User,
          "https://github.com/vue-0",
          "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Alex Johnson",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-vue-2"),
          userId: new UserId("user-vue-2"),
          contactEmail: "vue-1@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(5),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-vue-2"),
          developerProfileId: new DeveloperProfileId("dev-vue-2"),
          projectItemId: new ProjectItemId("vue"),
          roles: [DeveloperRoleType.MAINTAINER],
          mergeRights: [MergeRightsType.REVIEWER],
          comment: "Security Expert",
          createdAt: yearAgo,
          updatedAt: hoursAgo(5),
        },
        developerOwner: new Owner(
          new OwnerId("vue-1"),
          OwnerType.User,
          "https://github.com/vue-1",
          "https://images.unsplash.com/photo-1570295999919-56ceb8e25514?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Emily Wong",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
    ],
  },

  // Kubernetes
  {
    projectItem: {
      id: new ProjectItemId("kubernetes"),
      projectItemType: ProjectItemType.GITHUB_REPOSITORY,
      sourceIdentifier: "kubernetes/kubernetes",
      createdAt: yearAgo,
      updatedAt: hoursAgo(1),
    },
    owner: new Owner(
      new OwnerId("kubernetes", 13629408),
      OwnerType.Organization,
      "https://github.com/kubernetes",
      "https://avatars.githubusercontent.com/u/13629408",
      undefined,
      undefined,
      undefined,
      undefined,
      "Kubernetes",
      undefined,
      undefined,
      "https://kubernetes.io",
      undefined,
      undefined,
    ),
    repository: new Repository(
      new RepositoryId(new OwnerId("kubernetes", 13629408), "kubernetes", 20580498),
      "https://github.com/kubernetes/kubernetes",
      "Production-Grade Container Orchestration for automating deployment and scaling.",
      "https://kubernetes.io",
      "Go",
      39000,
      108000,
      undefined,
      "kubernetes/kubernetes",
      false,
      ["containers", "orchestration", "devops"],
      undefined,
      undefined,
      undefined,
      undefined,
    ),
    developers: [
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-k8s-1"),
          userId: new UserId("user-k8s-1"),
          contactEmail: "kubernetes-0@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(1),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-k8s-1"),
          developerProfileId: new DeveloperProfileId("dev-k8s-1"),
          projectItemId: new ProjectItemId("kubernetes"),
          roles: [DeveloperRoleType.TSC_MEMBER, DeveloperRoleType.MAINTAINER],
          mergeRights: [MergeRightsType.FULL_COMMITTER, MergeRightsType.RELEASE_MANAGER],
          comment: "Core Maintainer",
          createdAt: yearAgo,
          updatedAt: hoursAgo(1),
        },
        developerOwner: new Owner(
          new OwnerId("kubernetes-0"),
          OwnerType.User,
          "https://github.com/kubernetes-0",
          "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "David Lee",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
    ],
  },

  // TensorFlow
  {
    projectItem: {
      id: new ProjectItemId("tensorflow"),
      projectItemType: ProjectItemType.GITHUB_REPOSITORY,
      sourceIdentifier: "tensorflow/tensorflow",
      createdAt: yearAgo,
      updatedAt: hoursAgo(3),
    },
    owner: new Owner(
      new OwnerId("tensorflow", 15658638),
      OwnerType.Organization,
      "https://github.com/tensorflow",
      "https://avatars.githubusercontent.com/u/15658638",
      undefined,
      undefined,
      undefined,
      undefined,
      "TensorFlow",
      undefined,
      undefined,
      "https://tensorflow.org",
      undefined,
      undefined,
    ),
    repository: new Repository(
      new RepositoryId(new OwnerId("tensorflow", 15658638), "tensorflow", 45717250),
      "https://github.com/tensorflow/tensorflow",
      "An end-to-end open source platform for machine learning applications.",
      "https://tensorflow.org",
      "Python",
      74000,
      185000,
      undefined,
      "tensorflow/tensorflow",
      false,
      ["machine-learning", "ai", "python"],
      undefined,
      undefined,
      undefined,
      undefined,
    ),
    developers: [
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-tf-1"),
          userId: new UserId("user-tf-1"),
          contactEmail: "tensorflow-0@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(3),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-tf-1"),
          developerProfileId: new DeveloperProfileId("dev-tf-1"),
          projectItemId: new ProjectItemId("tensorflow"),
          roles: [DeveloperRoleType.CORE_TEAM_MEMBER],
          mergeRights: [MergeRightsType.FULL_COMMITTER],
          comment: "Core Maintainer",
          createdAt: yearAgo,
          updatedAt: hoursAgo(3),
        },
        developerOwner: new Owner(
          new OwnerId("tensorflow-0"),
          OwnerType.User,
          "https://github.com/tensorflow-0",
          "https://images.unsplash.com/photo-1743850765931-4a00e4809a5f?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Sarah Chen",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-tf-2"),
          userId: new UserId("user-tf-2"),
          contactEmail: "tensorflow-1@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(3),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-tf-2"),
          developerProfileId: new DeveloperProfileId("dev-tf-2"),
          projectItemId: new ProjectItemId("tensorflow"),
          roles: [DeveloperRoleType.MAINTAINER, DeveloperRoleType.ACTIVE_CONTRIBUTOR],
          mergeRights: [MergeRightsType.REVIEWER],
          comment: "Security Expert",
          createdAt: yearAgo,
          updatedAt: hoursAgo(3),
        },
        developerOwner: new Owner(
          new OwnerId("tensorflow-1"),
          OwnerType.User,
          "https://github.com/tensorflow-1",
          "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Marcus Rodriguez",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
    ],
  },

  // Node.js
  {
    projectItem: {
      id: new ProjectItemId("nodejs"),
      projectItemType: ProjectItemType.GITHUB_REPOSITORY,
      sourceIdentifier: "nodejs/node",
      createdAt: yearAgo,
      updatedAt: hoursAgo(6),
    },
    owner: new Owner(
      new OwnerId("nodejs", 9950313),
      OwnerType.Organization,
      "https://github.com/nodejs",
      "https://avatars.githubusercontent.com/u/9950313",
      undefined,
      undefined,
      undefined,
      undefined,
      "Node.js",
      undefined,
      undefined,
      "https://nodejs.org",
      undefined,
      undefined,
    ),
    repository: new Repository(
      new RepositoryId(new OwnerId("nodejs", 9950313), "node", 27193779),
      "https://github.com/nodejs/node",
      "JavaScript runtime built on Chrome's V8 engine for scalable applications.",
      "https://nodejs.org",
      "JavaScript",
      28000,
      105000,
      undefined,
      "nodejs/node",
      false,
      ["runtime", "javascript", "backend"],
      undefined,
      undefined,
      undefined,
      undefined,
    ),
    developers: [
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-node-1"),
          userId: new UserId("user-node-1"),
          contactEmail: "nodejs-0@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: hoursAgo(6),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-node-1"),
          developerProfileId: new DeveloperProfileId("dev-node-1"),
          projectItemId: new ProjectItemId("nodejs"),
          roles: [DeveloperRoleType.TSC_MEMBER, DeveloperRoleType.CORE_TEAM_MEMBER],
          mergeRights: [MergeRightsType.FULL_COMMITTER],
          comment: "Core Maintainer",
          createdAt: yearAgo,
          updatedAt: hoursAgo(6),
        },
        developerOwner: new Owner(
          new OwnerId("nodejs-0"),
          OwnerType.User,
          "https://github.com/nodejs-0",
          "https://images.unsplash.com/photo-1526406915894-7bcd65f60845?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Priya Patel",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
    ],
  },

  // Linux Foundation (URL-based project, not on GitHub)
  {
    projectItem: {
      id: new ProjectItemId("linux-foundation"),
      projectItemType: ProjectItemType.URL,
      sourceIdentifier: "https://www.linuxfoundation.org",
      createdAt: yearAgo,
      updatedAt: daysAgo(2),
    },
    owner: null,
    repository: null,
    developers: [
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-lf-1"),
          userId: new UserId("user-lf-1"),
          contactEmail: "linux-foundation-0@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: daysAgo(2),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-lf-1"),
          developerProfileId: new DeveloperProfileId("dev-lf-1"),
          projectItemId: new ProjectItemId("linux-foundation"),
          roles: [DeveloperRoleType.BOARD_MEMBER, DeveloperRoleType.LINUX_FOUNDATION_FELLOW],
          mergeRights: [MergeRightsType.NONE],
          comment: "Board Member",
          createdAt: yearAgo,
          updatedAt: daysAgo(2),
        },
        developerOwner: new Owner(
          new OwnerId("lf-0"),
          OwnerType.User,
          "https://github.com/lf-0",
          "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "James Thompson",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
      {
        developerProfile: {
          id: new DeveloperProfileId("dev-lf-2"),
          userId: new UserId("user-lf-2"),
          contactEmail: "linux-foundation-1@example.com",
          onboardingCompleted: true,
          createdAt: yearAgo,
          updatedAt: daysAgo(2),
        },
        developerProjectItem: {
          id: new DeveloperProjectItemId("dpi-lf-2"),
          developerProfileId: new DeveloperProfileId("dev-lf-2"),
          projectItemId: new ProjectItemId("linux-foundation"),
          roles: [DeveloperRoleType.STEERING_COMMITTEE_MEMBER],
          mergeRights: [MergeRightsType.NONE],
          comment: "Steering Committee Member",
          createdAt: yearAgo,
          updatedAt: daysAgo(2),
        },
        developerOwner: new Owner(
          new OwnerId("lf-1"),
          OwnerType.User,
          "https://github.com/lf-1",
          "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400",
          undefined,
          undefined,
          undefined,
          undefined,
          "Rachel Kim",
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ),
      },
    ],
  },
];
