/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TermsAndConditionsRouteImport } from "./routes/terms-and-conditions"
import { Route as SponsorshipRouteImport } from "./routes/sponsorship"
import { Route as ServicesRouteImport } from "./routes/services"
import { Route as ProjectsRouteImport } from "./routes/projects"
import { Route as ProjectItemsDetailsRouteImport } from "./routes/project-items-details"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as PricingRouteImport } from "./routes/pricing"
import { Route as LogoutRouteImport } from "./routes/logout"
import { Route as FaqRouteImport } from "./routes/faq"
import { Route as DeveloperRouteImport } from "./routes/developer"
import { Route as ContactRouteImport } from "./routes/contact"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as CheckoutSuccessRouteImport } from "./routes/checkout/success"
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password"
import { Route as AuthPasswordRouteImport } from "./routes/auth/password"
import { Route as AuthIdentifyRouteImport } from "./routes/auth/identify"
import { Route as AuthGithubRouteImport } from "./routes/auth/github"
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password"
import { Route as AdminProjectRouteImport } from "./routes/admin/project"
import { Route as AdminMaintainersRouteImport } from "./routes/admin/maintainers"
import { Route as AdminInviteRepositoryUserRouteImport } from "./routes/admin/invite-repository-user"
import { Route as AdminInviteCompanyUserRouteImport } from "./routes/admin/invite-company-user"
import { Route as AdminCreateManualInvoiceRouteImport } from "./routes/admin/create-manual-invoice"
import { Route as AdminCreateCompanyRouteImport } from "./routes/admin/create-company"
import { Route as AdminCreateAddressRouteImport } from "./routes/admin/create-address"
import { Route as AuthenticatedDeveloperOnboardingCompletedRouteImport } from "./routes/_authenticated/developer-onboarding-completed"
import { Route as AuthenticatedDeveloperOnboardingRouteImport } from "./routes/_authenticated/developer-onboarding"
import { Route as ProjectOwnerParamIndexRouteImport } from "./routes/project/$ownerParam/index"
import { Route as ProjectOwnerParamRepoParamRouteImport } from "./routes/project/$ownerParam/$repoParam"
import { Route as AdminRepositoriesSyncRouteImport } from "./routes/admin/repositories/sync"
import { Route as AdminPlanCreateProductAndPriceRouteImport } from "./routes/admin/plan/create-product-and-price"
import { Route as AdminOrganizationsSyncRouteImport } from "./routes/admin/organizations/sync"
import { Route as AdminMaintainerGithubUsernameRouteImport } from "./routes/admin/maintainer/$githubUsername"
import { Route as AdminCampaignCreateProductAndPriceRouteImport } from "./routes/admin/campaign/create-product-and-price"

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: "/terms-and-conditions",
  path: "/terms-and-conditions",
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: "/sponsorship",
  path: "/sponsorship",
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectItemsDetailsRoute = ProjectItemsDetailsRouteImport.update({
  id: "/project-items-details",
  path: "/project-items-details",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: "/developer",
  path: "/developer",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: "/checkout/success",
  path: "/checkout/success",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordRoute = AuthPasswordRouteImport.update({
  id: "/auth/password",
  path: "/auth/password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdentifyRoute = AuthIdentifyRouteImport.update({
  id: "/auth/identify",
  path: "/auth/identify",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: "/auth/github",
  path: "/auth/github",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectRoute = AdminProjectRouteImport.update({
  id: "/project",
  path: "/project",
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintainersRoute = AdminMaintainersRouteImport.update({
  id: "/maintainers",
  path: "/maintainers",
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRepositoryUserRoute =
  AdminInviteRepositoryUserRouteImport.update({
    id: "/invite-repository-user",
    path: "/invite-repository-user",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInviteCompanyUserRoute = AdminInviteCompanyUserRouteImport.update({
  id: "/invite-company-user",
  path: "/invite-company-user",
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateManualInvoiceRoute =
  AdminCreateManualInvoiceRouteImport.update({
    id: "/create-manual-invoice",
    path: "/create-manual-invoice",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCreateCompanyRoute = AdminCreateCompanyRouteImport.update({
  id: "/create-company",
  path: "/create-company",
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateAddressRoute = AdminCreateAddressRouteImport.update({
  id: "/create-address",
  path: "/create-address",
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDeveloperOnboardingCompletedRoute =
  AuthenticatedDeveloperOnboardingCompletedRouteImport.update({
    id: "/developer-onboarding-completed",
    path: "/developer-onboarding-completed",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperOnboardingRoute =
  AuthenticatedDeveloperOnboardingRouteImport.update({
    id: "/developer-onboarding",
    path: "/developer-onboarding",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ProjectOwnerParamIndexRoute = ProjectOwnerParamIndexRouteImport.update({
  id: "/project/$ownerParam/",
  path: "/project/$ownerParam/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectOwnerParamRepoParamRoute =
  ProjectOwnerParamRepoParamRouteImport.update({
    id: "/project/$ownerParam/$repoParam",
    path: "/project/$ownerParam/$repoParam",
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRepositoriesSyncRoute = AdminRepositoriesSyncRouteImport.update({
  id: "/repositories/sync",
  path: "/repositories/sync",
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanCreateProductAndPriceRoute =
  AdminPlanCreateProductAndPriceRouteImport.update({
    id: "/plan/create-product-and-price",
    path: "/plan/create-product-and-price",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationsSyncRoute = AdminOrganizationsSyncRouteImport.update({
  id: "/organizations/sync",
  path: "/organizations/sync",
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintainerGithubUsernameRoute =
  AdminMaintainerGithubUsernameRouteImport.update({
    id: "/maintainer/$githubUsername",
    path: "/maintainer/$githubUsername",
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCampaignCreateProductAndPriceRoute =
  AdminCampaignCreateProductAndPriceRouteImport.update({
    id: "/campaign/create-product-and-price",
    path: "/campaign/create-product-and-price",
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/contact": typeof ContactRoute
  "/developer": typeof DeveloperRoute
  "/faq": typeof FaqRoute
  "/logout": typeof LogoutRoute
  "/pricing": typeof PricingRoute
  "/privacy": typeof PrivacyRoute
  "/project-items-details": typeof ProjectItemsDetailsRoute
  "/projects": typeof ProjectsRoute
  "/services": typeof ServicesRoute
  "/sponsorship": typeof SponsorshipRoute
  "/terms-and-conditions": typeof TermsAndConditionsRoute
  "/developer-onboarding": typeof AuthenticatedDeveloperOnboardingRoute
  "/developer-onboarding-completed": typeof AuthenticatedDeveloperOnboardingCompletedRoute
  "/admin/create-address": typeof AdminCreateAddressRoute
  "/admin/create-company": typeof AdminCreateCompanyRoute
  "/admin/create-manual-invoice": typeof AdminCreateManualInvoiceRoute
  "/admin/invite-company-user": typeof AdminInviteCompanyUserRoute
  "/admin/invite-repository-user": typeof AdminInviteRepositoryUserRoute
  "/admin/maintainers": typeof AdminMaintainersRoute
  "/admin/project": typeof AdminProjectRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/github": typeof AuthGithubRoute
  "/auth/identify": typeof AuthIdentifyRoute
  "/auth/password": typeof AuthPasswordRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/checkout/success": typeof CheckoutSuccessRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/campaign/create-product-and-price": typeof AdminCampaignCreateProductAndPriceRoute
  "/admin/maintainer/$githubUsername": typeof AdminMaintainerGithubUsernameRoute
  "/admin/organizations/sync": typeof AdminOrganizationsSyncRoute
  "/admin/plan/create-product-and-price": typeof AdminPlanCreateProductAndPriceRoute
  "/admin/repositories/sync": typeof AdminRepositoriesSyncRoute
  "/project/$ownerParam/$repoParam": typeof ProjectOwnerParamRepoParamRoute
  "/project/$ownerParam/": typeof ProjectOwnerParamIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/contact": typeof ContactRoute
  "/developer": typeof DeveloperRoute
  "/faq": typeof FaqRoute
  "/logout": typeof LogoutRoute
  "/pricing": typeof PricingRoute
  "/privacy": typeof PrivacyRoute
  "/project-items-details": typeof ProjectItemsDetailsRoute
  "/projects": typeof ProjectsRoute
  "/services": typeof ServicesRoute
  "/sponsorship": typeof SponsorshipRoute
  "/terms-and-conditions": typeof TermsAndConditionsRoute
  "/developer-onboarding": typeof AuthenticatedDeveloperOnboardingRoute
  "/developer-onboarding-completed": typeof AuthenticatedDeveloperOnboardingCompletedRoute
  "/admin/create-address": typeof AdminCreateAddressRoute
  "/admin/create-company": typeof AdminCreateCompanyRoute
  "/admin/create-manual-invoice": typeof AdminCreateManualInvoiceRoute
  "/admin/invite-company-user": typeof AdminInviteCompanyUserRoute
  "/admin/invite-repository-user": typeof AdminInviteRepositoryUserRoute
  "/admin/maintainers": typeof AdminMaintainersRoute
  "/admin/project": typeof AdminProjectRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/github": typeof AuthGithubRoute
  "/auth/identify": typeof AuthIdentifyRoute
  "/auth/password": typeof AuthPasswordRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/checkout/success": typeof CheckoutSuccessRoute
  "/admin": typeof AdminIndexRoute
  "/admin/campaign/create-product-and-price": typeof AdminCampaignCreateProductAndPriceRoute
  "/admin/maintainer/$githubUsername": typeof AdminMaintainerGithubUsernameRoute
  "/admin/organizations/sync": typeof AdminOrganizationsSyncRoute
  "/admin/plan/create-product-and-price": typeof AdminPlanCreateProductAndPriceRoute
  "/admin/repositories/sync": typeof AdminRepositoriesSyncRoute
  "/project/$ownerParam/$repoParam": typeof ProjectOwnerParamRepoParamRoute
  "/project/$ownerParam": typeof ProjectOwnerParamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/admin": typeof AdminRouteWithChildren
  "/contact": typeof ContactRoute
  "/developer": typeof DeveloperRoute
  "/faq": typeof FaqRoute
  "/logout": typeof LogoutRoute
  "/pricing": typeof PricingRoute
  "/privacy": typeof PrivacyRoute
  "/project-items-details": typeof ProjectItemsDetailsRoute
  "/projects": typeof ProjectsRoute
  "/services": typeof ServicesRoute
  "/sponsorship": typeof SponsorshipRoute
  "/terms-and-conditions": typeof TermsAndConditionsRoute
  "/_authenticated/developer-onboarding": typeof AuthenticatedDeveloperOnboardingRoute
  "/_authenticated/developer-onboarding-completed": typeof AuthenticatedDeveloperOnboardingCompletedRoute
  "/admin/create-address": typeof AdminCreateAddressRoute
  "/admin/create-company": typeof AdminCreateCompanyRoute
  "/admin/create-manual-invoice": typeof AdminCreateManualInvoiceRoute
  "/admin/invite-company-user": typeof AdminInviteCompanyUserRoute
  "/admin/invite-repository-user": typeof AdminInviteRepositoryUserRoute
  "/admin/maintainers": typeof AdminMaintainersRoute
  "/admin/project": typeof AdminProjectRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/github": typeof AuthGithubRoute
  "/auth/identify": typeof AuthIdentifyRoute
  "/auth/password": typeof AuthPasswordRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/checkout/success": typeof CheckoutSuccessRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/campaign/create-product-and-price": typeof AdminCampaignCreateProductAndPriceRoute
  "/admin/maintainer/$githubUsername": typeof AdminMaintainerGithubUsernameRoute
  "/admin/organizations/sync": typeof AdminOrganizationsSyncRoute
  "/admin/plan/create-product-and-price": typeof AdminPlanCreateProductAndPriceRoute
  "/admin/repositories/sync": typeof AdminRepositoriesSyncRoute
  "/project/$ownerParam/$repoParam": typeof ProjectOwnerParamRepoParamRoute
  "/project/$ownerParam/": typeof ProjectOwnerParamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/contact"
    | "/developer"
    | "/faq"
    | "/logout"
    | "/pricing"
    | "/privacy"
    | "/project-items-details"
    | "/projects"
    | "/services"
    | "/sponsorship"
    | "/terms-and-conditions"
    | "/developer-onboarding"
    | "/developer-onboarding-completed"
    | "/admin/create-address"
    | "/admin/create-company"
    | "/admin/create-manual-invoice"
    | "/admin/invite-company-user"
    | "/admin/invite-repository-user"
    | "/admin/maintainers"
    | "/admin/project"
    | "/auth/forgot-password"
    | "/auth/github"
    | "/auth/identify"
    | "/auth/password"
    | "/auth/reset-password"
    | "/checkout/success"
    | "/admin/"
    | "/admin/campaign/create-product-and-price"
    | "/admin/maintainer/$githubUsername"
    | "/admin/organizations/sync"
    | "/admin/plan/create-product-and-price"
    | "/admin/repositories/sync"
    | "/project/$ownerParam/$repoParam"
    | "/project/$ownerParam/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/contact"
    | "/developer"
    | "/faq"
    | "/logout"
    | "/pricing"
    | "/privacy"
    | "/project-items-details"
    | "/projects"
    | "/services"
    | "/sponsorship"
    | "/terms-and-conditions"
    | "/developer-onboarding"
    | "/developer-onboarding-completed"
    | "/admin/create-address"
    | "/admin/create-company"
    | "/admin/create-manual-invoice"
    | "/admin/invite-company-user"
    | "/admin/invite-repository-user"
    | "/admin/maintainers"
    | "/admin/project"
    | "/auth/forgot-password"
    | "/auth/github"
    | "/auth/identify"
    | "/auth/password"
    | "/auth/reset-password"
    | "/checkout/success"
    | "/admin"
    | "/admin/campaign/create-product-and-price"
    | "/admin/maintainer/$githubUsername"
    | "/admin/organizations/sync"
    | "/admin/plan/create-product-and-price"
    | "/admin/repositories/sync"
    | "/project/$ownerParam/$repoParam"
    | "/project/$ownerParam"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/admin"
    | "/contact"
    | "/developer"
    | "/faq"
    | "/logout"
    | "/pricing"
    | "/privacy"
    | "/project-items-details"
    | "/projects"
    | "/services"
    | "/sponsorship"
    | "/terms-and-conditions"
    | "/_authenticated/developer-onboarding"
    | "/_authenticated/developer-onboarding-completed"
    | "/admin/create-address"
    | "/admin/create-company"
    | "/admin/create-manual-invoice"
    | "/admin/invite-company-user"
    | "/admin/invite-repository-user"
    | "/admin/maintainers"
    | "/admin/project"
    | "/auth/forgot-password"
    | "/auth/github"
    | "/auth/identify"
    | "/auth/password"
    | "/auth/reset-password"
    | "/checkout/success"
    | "/admin/"
    | "/admin/campaign/create-product-and-price"
    | "/admin/maintainer/$githubUsername"
    | "/admin/organizations/sync"
    | "/admin/plan/create-product-and-price"
    | "/admin/repositories/sync"
    | "/project/$ownerParam/$repoParam"
    | "/project/$ownerParam/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DeveloperRoute: typeof DeveloperRoute
  FaqRoute: typeof FaqRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectItemsDetailsRoute: typeof ProjectItemsDetailsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SponsorshipRoute: typeof SponsorshipRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthGithubRoute: typeof AuthGithubRoute
  AuthIdentifyRoute: typeof AuthIdentifyRoute
  AuthPasswordRoute: typeof AuthPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProjectOwnerParamRepoParamRoute: typeof ProjectOwnerParamRepoParamRoute
  ProjectOwnerParamIndexRoute: typeof ProjectOwnerParamIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms-and-conditions": {
      id: "/terms-and-conditions"
      path: "/terms-and-conditions"
      fullPath: "/terms-and-conditions"
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sponsorship": {
      id: "/sponsorship"
      path: "/sponsorship"
      fullPath: "/sponsorship"
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/services": {
      id: "/services"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects": {
      id: "/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project-items-details": {
      id: "/project-items-details"
      path: "/project-items-details"
      fullPath: "/project-items-details"
      preLoaderRoute: typeof ProjectItemsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing": {
      id: "/pricing"
      path: "/pricing"
      fullPath: "/pricing"
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/logout": {
      id: "/logout"
      path: "/logout"
      fullPath: "/logout"
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/faq": {
      id: "/faq"
      path: "/faq"
      fullPath: "/faq"
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/developer": {
      id: "/developer"
      path: "/developer"
      fullPath: "/developer"
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contact": {
      id: "/contact"
      path: "/contact"
      fullPath: "/contact"
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/checkout/success": {
      id: "/checkout/success"
      path: "/checkout/success"
      fullPath: "/checkout/success"
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/reset-password": {
      id: "/auth/reset-password"
      path: "/auth/reset-password"
      fullPath: "/auth/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/password": {
      id: "/auth/password"
      path: "/auth/password"
      fullPath: "/auth/password"
      preLoaderRoute: typeof AuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/identify": {
      id: "/auth/identify"
      path: "/auth/identify"
      fullPath: "/auth/identify"
      preLoaderRoute: typeof AuthIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/github": {
      id: "/auth/github"
      path: "/auth/github"
      fullPath: "/auth/github"
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/auth/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/project": {
      id: "/admin/project"
      path: "/project"
      fullPath: "/admin/project"
      preLoaderRoute: typeof AdminProjectRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/maintainers": {
      id: "/admin/maintainers"
      path: "/maintainers"
      fullPath: "/admin/maintainers"
      preLoaderRoute: typeof AdminMaintainersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/invite-repository-user": {
      id: "/admin/invite-repository-user"
      path: "/invite-repository-user"
      fullPath: "/admin/invite-repository-user"
      preLoaderRoute: typeof AdminInviteRepositoryUserRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/invite-company-user": {
      id: "/admin/invite-company-user"
      path: "/invite-company-user"
      fullPath: "/admin/invite-company-user"
      preLoaderRoute: typeof AdminInviteCompanyUserRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/create-manual-invoice": {
      id: "/admin/create-manual-invoice"
      path: "/create-manual-invoice"
      fullPath: "/admin/create-manual-invoice"
      preLoaderRoute: typeof AdminCreateManualInvoiceRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/create-company": {
      id: "/admin/create-company"
      path: "/create-company"
      fullPath: "/admin/create-company"
      preLoaderRoute: typeof AdminCreateCompanyRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/create-address": {
      id: "/admin/create-address"
      path: "/create-address"
      fullPath: "/admin/create-address"
      preLoaderRoute: typeof AdminCreateAddressRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_authenticated/developer-onboarding-completed": {
      id: "/_authenticated/developer-onboarding-completed"
      path: "/developer-onboarding-completed"
      fullPath: "/developer-onboarding-completed"
      preLoaderRoute: typeof AuthenticatedDeveloperOnboardingCompletedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/developer-onboarding": {
      id: "/_authenticated/developer-onboarding"
      path: "/developer-onboarding"
      fullPath: "/developer-onboarding"
      preLoaderRoute: typeof AuthenticatedDeveloperOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/project/$ownerParam/": {
      id: "/project/$ownerParam/"
      path: "/project/$ownerParam"
      fullPath: "/project/$ownerParam/"
      preLoaderRoute: typeof ProjectOwnerParamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project/$ownerParam/$repoParam": {
      id: "/project/$ownerParam/$repoParam"
      path: "/project/$ownerParam/$repoParam"
      fullPath: "/project/$ownerParam/$repoParam"
      preLoaderRoute: typeof ProjectOwnerParamRepoParamRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/repositories/sync": {
      id: "/admin/repositories/sync"
      path: "/repositories/sync"
      fullPath: "/admin/repositories/sync"
      preLoaderRoute: typeof AdminRepositoriesSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/plan/create-product-and-price": {
      id: "/admin/plan/create-product-and-price"
      path: "/plan/create-product-and-price"
      fullPath: "/admin/plan/create-product-and-price"
      preLoaderRoute: typeof AdminPlanCreateProductAndPriceRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/organizations/sync": {
      id: "/admin/organizations/sync"
      path: "/organizations/sync"
      fullPath: "/admin/organizations/sync"
      preLoaderRoute: typeof AdminOrganizationsSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/maintainer/$githubUsername": {
      id: "/admin/maintainer/$githubUsername"
      path: "/maintainer/$githubUsername"
      fullPath: "/admin/maintainer/$githubUsername"
      preLoaderRoute: typeof AdminMaintainerGithubUsernameRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/campaign/create-product-and-price": {
      id: "/admin/campaign/create-product-and-price"
      path: "/campaign/create-product-and-price"
      fullPath: "/admin/campaign/create-product-and-price"
      preLoaderRoute: typeof AdminCampaignCreateProductAndPriceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDeveloperOnboardingRoute: typeof AuthenticatedDeveloperOnboardingRoute
  AuthenticatedDeveloperOnboardingCompletedRoute: typeof AuthenticatedDeveloperOnboardingCompletedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDeveloperOnboardingRoute: AuthenticatedDeveloperOnboardingRoute,
  AuthenticatedDeveloperOnboardingCompletedRoute:
    AuthenticatedDeveloperOnboardingCompletedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminCreateAddressRoute: typeof AdminCreateAddressRoute
  AdminCreateCompanyRoute: typeof AdminCreateCompanyRoute
  AdminCreateManualInvoiceRoute: typeof AdminCreateManualInvoiceRoute
  AdminInviteCompanyUserRoute: typeof AdminInviteCompanyUserRoute
  AdminInviteRepositoryUserRoute: typeof AdminInviteRepositoryUserRoute
  AdminMaintainersRoute: typeof AdminMaintainersRoute
  AdminProjectRoute: typeof AdminProjectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCampaignCreateProductAndPriceRoute: typeof AdminCampaignCreateProductAndPriceRoute
  AdminMaintainerGithubUsernameRoute: typeof AdminMaintainerGithubUsernameRoute
  AdminOrganizationsSyncRoute: typeof AdminOrganizationsSyncRoute
  AdminPlanCreateProductAndPriceRoute: typeof AdminPlanCreateProductAndPriceRoute
  AdminRepositoriesSyncRoute: typeof AdminRepositoriesSyncRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateAddressRoute: AdminCreateAddressRoute,
  AdminCreateCompanyRoute: AdminCreateCompanyRoute,
  AdminCreateManualInvoiceRoute: AdminCreateManualInvoiceRoute,
  AdminInviteCompanyUserRoute: AdminInviteCompanyUserRoute,
  AdminInviteRepositoryUserRoute: AdminInviteRepositoryUserRoute,
  AdminMaintainersRoute: AdminMaintainersRoute,
  AdminProjectRoute: AdminProjectRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCampaignCreateProductAndPriceRoute:
    AdminCampaignCreateProductAndPriceRoute,
  AdminMaintainerGithubUsernameRoute: AdminMaintainerGithubUsernameRoute,
  AdminOrganizationsSyncRoute: AdminOrganizationsSyncRoute,
  AdminPlanCreateProductAndPriceRoute: AdminPlanCreateProductAndPriceRoute,
  AdminRepositoriesSyncRoute: AdminRepositoriesSyncRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DeveloperRoute: DeveloperRoute,
  FaqRoute: FaqRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectItemsDetailsRoute: ProjectItemsDetailsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SponsorshipRoute: SponsorshipRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthGithubRoute: AuthGithubRoute,
  AuthIdentifyRoute: AuthIdentifyRoute,
  AuthPasswordRoute: AuthPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProjectOwnerParamRepoParamRoute: ProjectOwnerParamRepoParamRoute,
  ProjectOwnerParamIndexRoute: ProjectOwnerParamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
